import type { Metadata } from "next";
import Link from "next/link";
import {
  DocPage,
  DocSection,
  DocSubheading,
} from "@/components/DocPage";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { legal } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Blazeball Privacy Policy",
  description:
    "Privacy Policy for the Blazeball mobile game by RAKN LABS (com.raknlabs.blazeball).",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <>
      <Navbar />
      <main className="pt-[var(--nav-h)]">
        <DocPage
          kicker="Legal"
          title="Privacy Policy — Blazeball"
          meta={
            <>
              Application: <strong>Blazeball</strong> (Android package{" "}
              <code>{legal.blazeball.packageName}</code>)
              <br />
              Operator: <strong>RAKN LABS</strong>
              <br />
              Website:{" "}
              <a href={legal.siteUrl}>{legal.siteUrl.replace("https://", "")}</a>
              <br />
              Effective date: {legal.effectiveDate}
              <br />
              Last updated: {legal.lastUpdated}
            </>
          }
        >
          <DocSection index="01" title="Introduction">
            <p>
              This Privacy Policy explains how RAKN LABS (&ldquo;we&rdquo;,
              &ldquo;us&rdquo;, &ldquo;our&rdquo;) collects, uses, stores, and
              shares information when you use the mobile game{" "}
              <strong>Blazeball</strong> (the &ldquo;App&rdquo;). It applies
              specifically to Blazeball and to related online services that
              support the App (account, cloud save, and multiplayer).
            </p>
            <p>
              By creating an account or using online features of the App, you
              acknowledge this Policy. If you do not agree, please do not create
              an account or use those online features.
            </p>
          </DocSection>

          <DocSection index="02" title="Who is responsible">
            <p>
              Data controller: <strong>RAKN LABS</strong>
              <br />
              Public site:{" "}
              <a href={legal.siteUrl}>{legal.siteUrl.replace("https://", "")}</a>
              <br />
              Privacy contact email:{" "}
              <a href={`mailto:${legal.privacyEmail}`}>{legal.privacyEmail}</a>
            </p>
            <p>
              You can also contact us through Google Play Console using the
              developer contact details listed for RAKN LABS / Blazeball.
            </p>
          </DocSection>

          <DocSection index="03" title="Information we collect">
            <p>
              We collect only what is needed to run accounts, save progress, and
              operate online play.
            </p>

            <DocSubheading>3.1 Account and identity data</DocSubheading>
            <ul>
              <li>
                <strong>Email address</strong> — provided when you register with
                email/password, or obtained from Google when you sign in with
                Google.
              </li>
              <li>
                <strong>User ID</strong> — a unique account identifier generated
                by our authentication system (Supabase Auth).
              </li>
              <li>
                <strong>Authentication tokens</strong> — access/refresh tokens
                stored securely on your device to keep you signed in.
              </li>
              <li>
                <strong>Optional profile display name</strong> — if you set one
                in the App.
              </li>
            </ul>

            <DocSubheading>
              3.2 Gameplay and progression data (generated by the App)
            </DocSubheading>
            <ul>
              <li>Campaign / league map progress</li>
              <li>Blazer levels, XP, skills and unlocks</li>
              <li>
                Inventory, cosmetics / skins, shop entitlements and currencies
              </li>
              <li>Achievements, career stats and account level</li>
              <li>
                Social features data such as friend relationships and invite /
                referral codes
              </li>
              <li>Match-related gameplay state needed for online sessions</li>
            </ul>

            <DocSubheading>3.3 Device and technical data</DocSubheading>
            <ul>
              <li>
                Local preferences and settings stored on device (for example
                audio and control options)
              </li>
              <li>
                Basic technical information required by our service providers to
                deliver networking and account services (such as IP address
                processed by those providers, connection metadata, and platform
                identifiers used by Android / Google Play services)
              </li>
            </ul>

            <DocSubheading>
              3.4 What we do not intentionally collect
            </DocSubheading>
            <ul>
              <li>Precise GPS location</li>
              <li>
                Contacts, photos, microphone, or camera content (unless a future
                feature asks permission and updates this Policy)
              </li>
              <li>
                Government ID or payment card numbers entered into Blazeball
                itself (purchases, if any, are processed by Google Play)
              </li>
            </ul>
          </DocSection>

          <DocSection index="04" title="How we collect information">
            <ul>
              <li>
                <strong>Directly from you</strong> — email/password
                registration, Google Sign-In, profile edits, and in-app actions.
              </li>
              <li>
                <strong>Automatically through the App</strong> — progress,
                inventory and other gameplay state when you play and when cloud
                sync runs.
              </li>
              <li>
                <strong>From third-party authentication</strong> — if you choose
                Google Sign-In, Google provides account email / identity data
                needed to create or link your Blazeball account.
              </li>
            </ul>
          </DocSection>

          <DocSection index="05" title="Why we use your information">
            <ul>
              <li>Create and secure your account and keep you signed in</li>
              <li>Save and restore your game progress across devices</li>
              <li>Enable online multiplayer matchmaking and gameplay</li>
              <li>Provide social / friend and invite features</li>
              <li>Operate the in-game shop and entitlements</li>
              <li>
                Prevent abuse, debug issues, and maintain service reliability
              </li>
              <li>
                Comply with legal obligations and Google Play requirements
                (including account deletion)
              </li>
              <li>Respond to privacy or support requests</li>
            </ul>
            <p>
              Legal bases (where applicable, e.g. GDPR): performance of a
              contract (providing the game service), legitimate interests
              (security, anti-abuse, service improvement), and consent where
              required (for example optional Google Sign-In).
            </p>
          </DocSection>

          <DocSection index="06" title="How we share information">
            <p>
              We do <strong>not sell</strong> your personal information. We
              share data only with service providers that help us operate
              Blazeball, under their own terms and privacy policies:
            </p>
            <ul>
              <li>
                <strong>Supabase</strong> (backend / database / authentication
                hosting) — stores account credentials metadata (email), user
                IDs, and cloud game progress. Policy:{" "}
                <a
                  href="https://supabase.com/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  supabase.com/privacy
                </a>
              </li>
              <li>
                <strong>Photon / Exit Games (Photon Fusion)</strong> —
                multiplayer networking and matchmaking. Connection and session
                data necessary to join and play online matches may be processed.
                Policy:{" "}
                <a
                  href="https://dashboard.photonengine.com/account/privacyandcookiepolicy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Photon privacy policy
                </a>
              </li>
              <li>
                <strong>Google</strong> — Google Play distribution, Google Play
                Services, and optional Google Sign-In; if you buy digital items,
                Google Play Billing processes the transaction. Policy:{" "}
                <a
                  href="https://policies.google.com/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  policies.google.com/privacy
                </a>
              </li>
              <li>
                <strong>Vercel</strong> — hosts this public website / privacy
                page only (not your Blazeball gameplay database). Policy:{" "}
                <a
                  href="https://vercel.com/legal/privacy-policy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  vercel.com/legal/privacy-policy
                </a>
              </li>
            </ul>
            <p>
              We may also disclose information if required by law, legal
              process, or to protect the rights, safety, and integrity of
              players and RAKN LABS.
            </p>
          </DocSection>

          <DocSection index="07" title="Data storage and retention">
            <ul>
              <li>
                Account and cloud progress are stored on Supabase infrastructure
                while your account exists.
              </li>
              <li>
                Session tokens and local settings are stored on your device.
              </li>
              <li>
                Multiplayer session data is processed transiently to run matches.
              </li>
              <li>
                When you delete your account in the App (Options → Account →
                Delete my account), we delete your authentication user and
                associated cloud progress cascading from that account, and we
                clear local account data on the device used for deletion.
              </li>
              <li>
                Backup or log copies held by providers may persist for a limited
                technical period according to their systems.
              </li>
            </ul>
          </DocSection>

          <DocSection index="08" title="Account deletion">
            <p>
              You can delete your Blazeball account and associated cloud data
              from the{" "}
              <Link href="/delete-account">account deletion page</Link>, or from
              inside the App:{" "}
              <strong>Options → Account → Delete my account</strong>, then
              confirm.
            </p>
            <p>
              You may also email{" "}
              <a href={`mailto:${legal.privacyEmail}`}>{legal.privacyEmail}</a>{" "}
              from the email address linked to your account to request deletion.
              We will process verified requests within a reasonable period and no
              later than applicable legal deadlines.
            </p>
          </DocSection>

          <DocSection index="09" title="Your rights">
            <p>
              Depending on your country (including EEA/UK and similar laws), you
              may have rights to:
            </p>
            <ul>
              <li>Access the personal data we hold about you</li>
              <li>Correct inaccurate data</li>
              <li>Delete your account and related personal data</li>
              <li>Object to or restrict certain processing</li>
              <li>Data portability, where applicable</li>
              <li>Withdraw consent where processing is consent-based</li>
            </ul>
            <p>
              To exercise these rights, use in-App account deletion where
              available or contact{" "}
              <a href={`mailto:${legal.privacyEmail}`}>{legal.privacyEmail}</a>.
            </p>
          </DocSection>

          <DocSection index="10" title="Children">
            <p>
              Blazeball is not directed at children under 13 (or the minimum age
              required in your country). We do not knowingly collect personal
              information from children under that age. If you believe a child
              has created an account, contact us and we will take appropriate
              steps to delete the account and related data.
            </p>
          </DocSection>

          <DocSection index="11" title="Security">
            <p>
              We use industry-standard protections appropriate to an online game
              account system (encrypted transport via HTTPS/TLS to our backends,
              authenticated API access, and account deletion controls). No method
              of transmission or storage is 100% secure.
            </p>
          </DocSection>

          <DocSection index="12" title="International transfers">
            <p>
              Our service providers may process data in data centers outside your
              country (for example EU and/or US regions used by Supabase, Photon,
              Google, or Vercel). Where required, transfers rely on appropriate
              safeguards offered by those providers.
            </p>
          </DocSection>

          <DocSection index="13" title="Changes to this Policy">
            <p>
              We may update this Privacy Policy to reflect product, legal, or
              provider changes. The &ldquo;Last updated&rdquo; date at the top
              will change when we do. Continued use of the App after an update
              means you accept the revised Policy, except where additional
              consent is required by law.
            </p>
          </DocSection>

          <DocSection index="14" title="Contact">
            <p>
              RAKN LABS — Blazeball Privacy
              <br />
              Email:{" "}
              <a href={`mailto:${legal.privacyEmail}`}>{legal.privacyEmail}</a>
              <br />
              Web:{" "}
              <a href={legal.siteUrl}>{legal.siteUrl.replace("https://", "")}</a>
            </p>
          </DocSection>

          <p className="border-t border-white/10 pt-8 text-sm text-white/35">
            This page is the public Privacy Policy for Blazeball (
            <code className="font-mono">{legal.blazeball.packageName}</code>).
          </p>
        </DocPage>
      </main>
      <Footer />
    </>
  );
}
